# -*- coding: utf-8 -*-
"""Muhammad Rafi Irfan-Pertemuan02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZQlwkH3SVk3HnhyQuaLrWq7o1RG7KAy

MK DAA Latihan Pertemuan ke-2
"""

import numpy as np

#Terdapat list a dan b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#lalu jumlahkan
hasil = a + b

NpHasil = np.sum(a+b)

print(NpHasil)

print("Numpy Version " + np.__version__)

nilai_siswa = np.array([85, 55, 40, 90])

print(nilai_siswa[3])

def getSum(myList):
  sum = 0
  for i in myList:
    sum = sum + i
  return sum

add_a_b = np.add(a, b)
getSum(add_a_b)

def getSum2(myList):
  sum = 0
  for row in myList:
    for i in row:
      sum += i
  return sum

getSum2([[1, 2, 3], [4, 5, 6]])

def getBagi(myList):
  bagi = 0
  for i in myList:
    bagi = bagi * i

getBagi([60, 3, 3])

nama = input("Masukkan Nama: ")
nim = int(input("Masukkan NIM: "))
print("Hello World!")
print(f"Nama saya{nama}")

print(f"NIM saya {nim}")

if 5>2:
  print("Five is greater than two!")

x = 5
y = "John"
print(x)
print(y)

x = 4
x = "Sally"
print(x)

def getFirst(list):
  return list[0]

getFirst(a)

def getSecond(list):
  return list[1]

getFirst(a)

def getLast(list):
  return list[-1]

getFirst(a)

def getLast2(list):
  size = len(list)
  return list[size]

getFirst(a)